// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaudagljixmhxqmozjpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdWRhZ2xqaXhtaHhxbW96anB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDAxNjIsImV4cCI6MjA2NjAxNjE2Mn0.0hjt_iGizZ_j_pNW_gavqjA_PU4xYYT3l7xut8Lh0F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);